x=input('Enter length of one side ');
y=input('Enter length of adjacent side ');
a=input('Enter distance from origin ');
alpha=input('Enter angle between adjacent sides ');
omega=input('Enter angular velocity ');
t=0:0.05:(2*pi/omega);
theta=omega*t;
p0=[0;0];
p1=[a*cos(theta)+y*cos(theta+alpha);y*sin(theta+alpha)+a*sin(theta)];
p2=[x*cos(theta)+y*cos(theta+alpha);y*sin(theta+alpha)+x*sin(theta)];
p3=[x*cos(theta);x*sin(theta)];
p4=[a*cos(theta);a*sin(theta)];
m12=[(p1(1,1)+p2(1,1))/2,(p1(2,1)+p2(2,2))/2];
p1_x=p1(1,:);
p1_y=p1(2,:);
p1_vx=diff(p1_x)./diff(t);
p1_vy=diff(p1_y)./diff(t);
p1_v=sqrt(p1_vx.^2+p1_vy.^2);
p2_x=p2(1,:);
p2_y=p2(2,:);
p2_vx=diff(p2_x)./diff(t);
p2_vy=diff(p2_y)./diff(t);
p2_v=sqrt(p2_vx.^2+p2_vy.^2);
p3_x=p3(1,:);
p3_y=p3(2,:);
p3_vx=diff(p3_x)./diff(t);
p3_vy=diff(p3_y)./diff(t);
p3_v=sqrt(p3_vx.^2+p3_vy.^2);
p4_x=p4(1,:);
p4_y=p4(2,:);
p4_vx=diff(p4_x)./diff(t);
p4_vy=diff(p4_y)./diff(t);
p4_v=sqrt(p4_vx.^2+p4_vy.^2);
for i=1:length(t)
    plot1=subplot(1,1,1);
    title('Pantograph Motion');
    text(0,0,'origin');
    p0_circle=viscircles(p0',0.1);
    p1_circle=viscircles(p1(:,i)',0.1);
    t1=text(p1(1,i),p1(2,i),' P1');
    p2_circle=viscircles(p2(:,i)',0.1);
    t2=text(p2(1,i),p2(2,i),' P2');
    p3_circle=viscircles(p3(:,i)',0.1);
    t3=text(p3(1,i),p3(2,i),' P3');
    p4_circle=viscircles(p4(:,i)',0.1);
    t4=text(p4(1,i),p4(2,i),' P4');
    link_a=line([p1(1,i) p2(1,i)],[p1(2,i) p2(2,i)]);
    link_b=line([p2(1,i) p3(1,i)],[p2(2,i) p3(2,i)]);
    link_c=line([p3(1,i) p4(1,i)],[p3(2,i) p4(2,i)]);
    link_d=line([p1(1,i) p4(1,i)],[p1(2,i) p4(2,i)]);
    m12=(p1(:,i)+p2(:,i))/2;
    m23=(p2(:,i)+p3(:,i))/2;
    m34=(p3(:,i)+p4(:,i))/2;
    m41=(p4(:,i)+p1(:,i))/2;
    mid12=viscircles(m12',0.01,'Color','r');
    mid23=viscircles(m23',0.01,'Color','g');
    mid34=viscircles(m34',0.01,'Color','b');
    mid41=viscircles(m41',0.01,'Color','y');
    %change the range of axes on the plot
    axis([-15 15 -15 15]); 
    pause(0.005);
    if(i<length(t))
        delete(p0_circle);
        delete(p1_circle);
        delete(p2_circle);
        delete(p3_circle);
        delete(p4_circle);
        delete(link_a);
        delete(link_b);
        delete(link_c);
        delete(link_d);
        delete(t1);
        delete(t2);
        delete(t3);
        delete(t4);
        
        %plot2=subplot(4,4,3);
        %plot(plot2,t(1:i),p1_v(1:i));
        %axis([0 t(end) 0 5]);
        %grid on;
        %plot3=subplot(4,4,4);
        %plot(plot3,t(1:i),p2_v(1:i));
        %axis([0 t(end) 0 10]);
        %grid on;
        %plot4=subplot(4,4,5);
        %plot(plot4,t(1:i),p3_v(1:i));
        %axis([0 t(end) 0 25]);
        %grid on;
        %plot5=subplot(4,4,6);
        %plot(plot5,t(1:i),p4_v(1:i));
        %axis([0 t(end) 0 25]);
        %grid on;
    end
end